### ISSUE TITLE
SingleOrDefault error

### ISSUE THREAD

**Issue by schmuli** [Reactive-Extensions/IxJS#9]
Hi!

Just looking through the code, I noticed that when calling <code>singleOrDefault</code> with a predicate, the call is first forwarded to <code>where</code>, and then a single result is returned from that.
In <b>src/core/enumerable.js</b> (line 982):

    EnumerablePrototype.singleOrDefault = function (predicate) {
        if (predicate) {
            return this.where(predicate).single();
        }
        ...
    }

if I'm not mistaken, shouldn't that be a call to <code>singleOrDefault()</code>, rather than <code>single()</code>?

**Comment by elmerbulthuis** [comment]
fixed it in  #17
